blog/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = patterns('',
    url(r'^tag/(?P<tag>[-\w]+)/', views.tag_view, name="tag"),
    url(r'^category/(?P<category>[-\w]+)/feed/$', views.LatestCategoryFeed(), name="category_feed"),
    url(r'^category/(?P<category>[-\w]+)/', views.category_view, name="category"),
    url(r'^author/(?P<author>[-\w]+)/', views.author_view, name="author"),
)

carvertiseblog/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls

from search import views as search_views


urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    url(r'', include(wagtail_urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.generic import TemplateView

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.core.exceptions import ValidationError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Count, Q
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
# from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailcore.models import Page
from wagtail.wagtailadmin.edit_handlers import (
    FieldPanel, InlinePanel, MultiFieldPanel, FieldRowPanel)
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailsearch import index
from taggit.models import TaggedItemBase, Tag
from modelcluster.tags import ClusterTaggableManager
from modelcluster.fields import ParentalKey
import datetime


# StreamField
from wagtail.wagtailcore.fields import StreamField
from wagtail.wagtailcore import blocks
from wagtail.wagtailimages.blocks import ImageChooserBlock
from wagtail.wagtailembeds.blocks import EmbedBlock
from wagtail.wagtailadmin.edit_handlers import FieldPanel, FieldRowPanel, MultiFieldPanel, \
    InlinePanel, PageChooserPanel, StreamFieldPanel


COMMENTS_APP = getattr(settings, 'COMMENTS_APP', None)


def get_blog_context(context):
    """ Get context data useful on all blog related pages """
    context['authors'] = get_user_model().objects.filter(
        owned_pages__live=True,
        owned_pages__content_type__model='blogpage'
    ).annotate(Count('owned_pages')).order_by('-owned_pages__count')
    context['all_categories'] = BlogCategory.objects.all()
    context['root_categories'] = BlogCategory.objects.filter(
        parent=None,
    ).prefetch_related(
        'children',
    ).annotate(
        blog_count=Count('blogpage'),
    )
    return context


class BlogIndexPage(Page):
    @property
    def blogs(self):
        # Get list of blog pages that are descendants of this page
        blogs = BlogPage.objects.descendant_of(self).live()
        blogs = blogs.order_by(
            '-date'
        ).select_related('owner').prefetch_related(
            'tagged_items__tag',
            'categories',
            'categories__category',
        )
        return blogs

    def get_context(self, request, tag=None, category=None, author=None, *args,
                    **kwargs):
        context = super(BlogIndexPage, self).get_context(
            request, *args, **kwargs)
        blogs = self.blogs

        if tag is None:
            tag = request.GET.get('tag')
        if tag:
            blogs = blogs.filter(tags__slug=tag)
        if category is None:  # Not coming from category_view in views.py
            if request.GET.get('category'):
                category = get_object_or_404(
                    BlogCategory, slug=request.GET.get('category'))
        if category:
            if not request.GET.get('category'):
                category = get_object_or_404(BlogCategory, slug=category)
            blogs = blogs.filter(categories__category__name=category)
        if author:
            if isinstance(author, str) and not author.isdigit():
                blogs = blogs.filter(author__username=author)
            else:
                blogs = blogs.filter(author_id=author)

        # Pagination
        page = request.GET.get('page')
        page_size = 10
        if hasattr(settings, 'BLOG_PAGINATION_PER_PAGE'):
            page_size = settings.BLOG_PAGINATION_PER_PAGE

        if page_size is not None:
            paginator = Paginator(blogs, page_size)  # Show 10 blogs per page
            try:
                blogs = paginator.page(page)
            except PageNotAnInteger:
                blogs = paginator.page(1)
            except EmptyPage:
                blogs = paginator.page(paginator.num_pages)

        context['blogs'] = blogs
        context['category'] = category
        context['tag'] = tag
        context['author'] = author
        context['COMMENTS_APP'] = COMMENTS_APP
        context = get_blog_context(context)

        return context

    class Meta:
        verbose_name = _('Blog index')
    subpage_types = ['blog.BlogPage']


@register_snippet
class BlogCategory(models.Model):
    name = models.CharField(
        max_length=80, unique=True, verbose_name=_('Category Name'))
    slug = models.SlugField(unique=True, max_length=80)
    parent = models.ForeignKey(
        'self', blank=True, null=True, related_name="children",
        help_text=_(
            'Categories, unlike tags, can have a hierarchy. You might have a '
            'Jazz category, and under that have children categories for Bebop'
            ' and Big Band. Totally optional.')
    )
    description = models.CharField(max_length=500, blank=True)

    class Meta:
        ordering = ['name']
        verbose_name = _("Blog Category")
        verbose_name_plural = _("Blog Categories")

    panels = [
        FieldPanel('name'),
        FieldPanel('parent'),
        FieldPanel('description'),
    ]

    def __str__(self):
        return self.name

    def clean(self):
        if self.parent:
            parent = self.parent
            if self.parent == self:
                raise ValidationError('Parent category cannot be self.')
            if parent.parent and parent.parent == self:
                raise ValidationError('Cannot have circular Parents.')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super(BlogCategory, self).save(*args, **kwargs)


class BlogCategoryBlogPage(models.Model):
    category = models.ForeignKey(
        BlogCategory, related_name="+", verbose_name=_('Category'))
    page = ParentalKey('BlogPage', related_name='categories')
    panels = [
        FieldPanel('category'),
    ]


class BlogPageTag(TaggedItemBase):
    content_object = ParentalKey('BlogPage', related_name='tagged_items')


@register_snippet
class BlogTag(Tag):
    class Meta:
        proxy = True
# Two Column block
# class TwoColumnBlock(blocks.StructBlock):
#
#     background = blocks.ChoiceBlock(default="white")
#     left_column = blocks.StreamBlock([
#             ('heading', blocks.CharBlock(classname="full title")),
#             ('paragraph', blocks.RichTextBlock()),
#             ('image', ImageChooserBlock()),
#             ('embedded_video', EmbedBlock()),
#         ], icon='arrow-left', label='Left column content')
#
#     right_column = blocks.StreamBlock([
#             ('heading', blocks.CharBlock(classname="full title")),
#             ('paragraph', blocks.RichTextBlock()),
#             ('image', ImageChooserBlock()),
#             ('embedded_video', EmbedBlock()),
#         ], icon='arrow-right', label='Right column content')
#
#     class Meta:
#         template = 'yourapp/blocks/two_column_block.html'
#         icon = 'placeholder'
#         label = 'Two Columns'

LIMIT_AUTHOR_CHOICES = getattr(settings, 'BLOG_LIMIT_AUTHOR_CHOICES_GROUP', None)
if LIMIT_AUTHOR_CHOICES:
    limit_author_choices = {'groups__name': LIMIT_AUTHOR_CHOICES}
else:
    limit_author_choices = {'is_staff': True}
class BlogPage(Page):
    # change RichTextField to StreamField!!!!!!!!!
    # body = RichTextField(verbose_name=_('body'))
    body = StreamField([
        ('heading', blocks.CharBlock(classname="full title", icon="title")),
        ('paragraph', blocks.RichTextBlock()),
        ('image', ImageChooserBlock(icon="image")),
        # ('two_columns', TwoColumnBlock()),
        ('embedded_video', EmbedBlock(icon="media")), ], null=True, blank=True, verbose_name=_('body'),)
    tags = ClusterTaggableManager(through=BlogPageTag, blank=True)
    date = models.DateField(
        _("Post date"), default=datetime.datetime.today,
        help_text=_("This date may be displayed on the blog post. It is not "
                    "used to schedule posts to go live at a later date.")
    )
    header_image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
        verbose_name=_('Header image')
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True, null=True,
        limit_choices_to=limit_author_choices,
        verbose_name=_('Author'),
        on_delete=models.SET_NULL,
        related_name='author_pages',
    )

    search_fields = Page.search_fields + (
        index.SearchField('body'),
    )
    blog_categories = models.ManyToManyField(
        BlogCategory, through=BlogCategoryBlogPage, blank=True)

    settings_panels = [
        MultiFieldPanel([
            FieldRowPanel([
                FieldPanel('go_live_at'),
                FieldPanel('expire_at'),
            ], classname="label-above"),
        ], 'Scheduled publishing', classname="publishing"),
        FieldPanel('date'),
        FieldPanel('author'),
    ]

    def save_revision(self, *args, **kwargs):
        if not self.author:
            self.author = self.owner
        return super(BlogPage, self).save_revision(*args, **kwargs)

    def get_absolute_url(self):
        return self.url

    def get_blog_index(self):
        # Find closest ancestor which is a blog index
        return self.get_ancestors().type(BlogIndexPage).last()

    def get_context(self, request, *args, **kwargs):
        context = super(BlogPage, self).get_context(request, *args, **kwargs)
        context['blogs'] = self.get_blog_index().blogindexpage.blogs
        context = get_blog_context(context)
        context['COMMENTS_APP'] = COMMENTS_APP
        return context

    class Meta:
        verbose_name = _('Blog page')
        verbose_name_plural = _('Blog pages')
        ordering = ['-date']

    parent_page_types = ['blog.BlogIndexPage']


BlogPage.content_panels = [
    FieldPanel('title', classname="full title"),

blog/views.py
from django.contrib.syndication.views import Feed
from .models import BlogIndexPage, BlogPage, BlogCategory
from django.shortcuts import get_object_or_404


def tag_view(request, tag):
    index = BlogIndexPage.objects.first()
    return index.serve(request, tag=tag)


def category_view(request, category):
    index = BlogIndexPage.objects.first()
    return index.serve(request, category=category)


def author_view(request, author):
    index = BlogIndexPage.objects.first()
    return index.serve(request, author=author)


class LatestEntriesFeed(Feed):
    title = "Blog"
    link = "/blog/"
    description = "A Blog"

    def items(self):
        return BlogPage.objects.order_by('-date')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body


class LatestCategoryFeed(Feed):
    description = "A Blog"

    def title(self, category):
        return "Blog: " + category.name

    def link(self, category):
        return "/blog/category/" + category.slug

    def get_object(self, request, category):
        return get_object_or_404(BlogCategory, slug=category)

    def items(self, obj):
        return BlogPage.objects.filter(
            categories__category=obj).order_by('-date')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.body

blog/templates/blog/blog_index_page.html
<div class='header'>
<h1>Blog</h1>
</div>

<!-- Top bar  -->
  <header  class="nav-down">
      <div class='carvertise_logo_top'><a href="carvertise.com">
      <img src='http://www.carvertise.com/img/logo.gif'>
    </a>
      </div>
      <div class='tabs_top'>
        <a class='single_tab' href="carvertise.com/gallery">gallery</a>
        <a class='single_tab' href="carvertise.com/case_study">case study</a>
        <a class='single_tab' href="carvertise.com/press">press</a>
        <a class='single_tab' href="/blog">blog</a>
        <a class='single_tab' href="carvertise.com/faq">FAQ</a>
      </div>
      <div class='tabs_top_mobile' onclick='mobile_menu();'>
        <img src='http://www.tax-consulting-group-san-diego.com/images/taxes-menu-icon.png'>

      </div>
  </header>


  <div class='main'>

{% extends "base.html" %}

{% load wagtailcore_tags static %}


{% block content %}
   {% if category %}
   <h2>{{ category }}</h2>
   {% endif %}
   {% if tag %}
   <h2>Posts tagged with '{{ tag }}'</h2>
   {% endif %}

   {% for rl in self.related_links.all %}
     <p>{{ rl.title }}: <a href='{{ rl.link_page.url }}'>{{ rl.link_page }}</a></p>
   {% endfor %}

   {% if blogs %}
       <ul class="list-unstyled the-loop">
       {% for blog in blogs %}
           <li class="blog-post-item{% if forloop.first and not category and not tag %} first-reset{% endif %}">
               {% include 'blog/blog_post.html' with include_context="index_page" %}
           </li>
       {% endfor %}
       </ul>
       <ul class="pager">
       {% if blogs.has_next %}
         <li class="previous"><a href="?page={{ blogs.next_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">&larr; Older</a></li>
       {% endif %}
       {% if blogs.has_previous %}
         <li class="next"><a href="?page={{ blogs.previous_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&amp;{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">Newer &rarr;</a></li>
       {% endif %}
       </ul>


   {% else %}
       <p>There are currently no blog posts</p>
   {% endif %}


      </div>
{% endblock %}

blog/templates/blog/blog_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}


{% block content %}

 {% include 'blog/blog_post.html' with blog=self %}

    {% if COMMENTS_APP == 'django_comments_xtd' %}
        {% include 'blog/blog_post_comments_xtd.html' with blog=self %}
    {% endif %}
{% endblock %}

blog/templates/blog/blog_post.html
{% load wagtailcore_tags static %}
{% if include_context == "index_page" %}
<a class="blog-post-link" href="{% pageurl blog %}">
  <h2>{{ blog.title }}</h2>
</a>

{% if blog.date %}
<div class="meta date">
  <i class="fa fa-calendar-o"></i> {{ blog.date|date:"F jS, Y" }}
  <i class="fa fa-pencil"></i> {{ blog.author }}
</div>
{% endif %}

<div class="blog-intro">
  <div class="blogmain">
    <div class="row">


<div  class="col-md-12 col-lg-12">


  {% for block in blog.body %}

    {% if block.block_type == 'heading' %}
    <div style="padding-left:6px;" class="myheading">
      {{block.value}}
      </div>
    {% endif %}

    {% if block.block_type == 'paragraph' %}
    <div class="myparagraph">

    </div>
    {% endif %}
    {% if block.block_type == 'image' %}
    <div class="myimage">

    </div>
    {% endif %}
    {% if block.block_type == 'embedded_video' %}
    <div class="myvideo">

    </div>
    {% endif %}
  {% if block.block_type == 'paragraph' %}
    <div style="padding-left:6px;" class='index-content'>
    {#{{ block.value|truncatewords_html:30 }}#}
  </div>
  {% endif %}

  {% endfor %}
      </div>
      </div>
  {#<a href="{% pageurl blog %}">Read the rest of this entry &raquo;</a>#}
</div>
</div>
{% else %}
<!-- Top bar  -->
  <header  class="nav-down post_nav">
      <div class='carvertise_logo_top'><a href="carvertise.com">
      <img src='http://www.carvertise.com/img/logo.gif'>
    </a>
      </div>
      <div class='tabs_top'>
        <a class='single_tab' href="carvertise.com/gallery">gallery</a>
        <a class='single_tab' href="carvertise.com/case_study">case study</a>
        <a class='single_tab' href="carvertise.com/press">press</a>
        <a class='single_tab' href="/blog">blog</a>
        <a class='single_tab' href="carvertise.com/faq">FAQ</a>
      </div>
      <div class='tabs_top_mobile' onclick='mobile_menu();'>
        <img src='http://www.tax-consulting-group-san-diego.com/images/taxes-menu-icon.png'>

      </div>
  </header>
<div class="blog-body">
<div class="blog-title">
  <h2>
  {{ blog.title }}
</h2>
</div>
<div class="meta">
  <div class="tags">
    {% if blog.tags.all %}
    Tags:
    {% for tag in blog.tags.all %}
    <a href="{% url 'blog:tag' tag.slug %}/">{{ tag }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% endif %}
  </div>

  </div>

<div class="blog-date">
  {% if blog.date %}
  <div class="meta date">
    {{ blog.date|date:"F jS, Y" }}
    {{ blog.author }}
  </div>
  {% endif %}
  </div>
  <div class="blog-content">


  {% for block in blog.body  %}
  {% if block.block_type == 'heading' %}
  <div class="myheading">
    {{block.value}}
    </div>
  {%else%}
    {{ block }}
  {% endif %}





  {% endfor %}
</div>
</div>
{% endif %}

<div class="share">
  <span class="st_linkedin_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="LinkedIn"></span>
  <span class="st_twitter_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Tweet"></span>
  <span class="st_facebook_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Facebook"></span>
  <span class="st_plusone_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Google +1"></span>
  <span class="st_email_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="Email"></span>
  <span class="st_sharethis_large" st_title="{{ blog.title }}" st_url="{{ SITE_URL }}{% pageurl blog %}" displayText="ShareThis"></span>
</div>

blog/templates/blog/blog_post_comments_xtd.html
{% load comments %}

{% render_comment_list for self %}
{% render_comment_form for self %}

blog/templates/blog/blog_post_comments_xtd_link.html
{% load wagtailcore_tags comments %}

{% get_comment_count for blog as comment_count %}
<p>
    <a href="{% pageurl blog %}#comments">
        {{ comment_count }} comment{{ comment_count|pluralize }}
    </a>
    {{ comment_count|pluralize:"has,have" }} been posted.
</p>